### ISSUE TITLE
What should the tool accept as inputs?

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/channel-narrowing-tool#1]
The goal of this tool is to take the instructions listed [here](http://etal.joewheaton.org/price-river-channel-analysis.html) and turn them into an automated tool. The page lists a number of steps, and I'm not sure how many of them we need to replicate.

The primary question that I have is, should we assume that the technician has already created a current and historic bankfull polygon? It seems to me that creating a historic bankfull polygon automatically would be difficult, since it's primarily based on imagery, but I'd like to confirm that impression with others before I move forward with that assumption.

@wally-mac and Geoff Stevens, can you weigh in on this?

**Comment by wally-mac** [comment]
Yes, you are correct "assume that the technician has already created a current and historic bankfull polygon".  I'll invite Geoff Stevens to join GitHub and have him weigh in.
