### ISSUE TITLE
Should we assume that the inputs will come with reach breaks?

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/channel-narrowing-tool#3]
One of the steps for channel narrowing is clipping both polygons to certain specified reach breaks. The steps about this are quoted below.

>C. Clip Both Polygons Using Specified Reach Breaks:
>1. Reach Breaks can be derived from several sources, in this case, a Valley Bottom Polygon broken up by Management Reaches was provided.
![Image of Tables](http://etal.joewheaton.org/uploads/7/1/4/2/71427833/pic10_1_orig.png)
>2. Other examples of potential reach breaks include:
> - GPS Waypoints (UTM-Northing, Easting) (Lat,Long)
> - Property Ownership Boundaries
> - Natural Geomorphic Breaks (Gradient, Valley Width, Substrate, Sinuosity)
> - Fixed Length Segmentation (ex. 500m segments)
>3. Cut historic and current bankfull channel polygons at reach breaks
> - Video demonstrating how to clip reaches by reach breaks:
> https://www.youtube.com/watch?v=a3stzy0OGC8

Should we try to automate this in the tool, or should we assume that the technician has done this already?

I'm sure there's a way to automate this, but I can't think of an easy one. We could see this functionality as a possible future enhancement, or we can do it now if we think it would be worth it. @wally-mac and @G-Stevens, what do you think?

**Comment by wally-mac** [comment]
@banderson1618 , I think it might be worth trying to automate this step if it's not too cumbersome.

**Comment by G-Stevens** [comment]
Scenario A: Use a segmented valley bottom polygon (by proportion or specified reach breaks) to divide historic and modern bankfull polygons.
Scenario B: Provide a polyline shapefile of reach breaks.
Scenario C: Use a valley bottom centerline to divide (segmented or reach break) historic  and modern bankfull polygons.

**Comment by G-Stevens** [comment]
This stuff may provide insight on A. whether or not we want to include segmentation in the tool, and B. to determine if there is way to segment 2 different polygons with the same segmented line. (For B, incorporate a VB polygon to derive a centerline from and segment that. http://gnat.riverscapes.xyz/Divide-Polygon-by-Segments     AND    https://github.com/Riverscapes/arcGNAT/blob/master/tools/DividePolygonBySegment.py
