### ISSUE TITLE
Creating a Centerline Seems Difficult

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/channel-narrowing-tool#4]
I've been researching the possibility of automatically creating a centerline for the tool, but none seem to be workable.

There's a support page [here](https://support.esri.com/en/technical-article/000012414) that is pretty easy to follow, but it requires some editing, and I can't think of a good way to replicate that editing in Python.

There's an ArcGIS Pro function called Polygon To Centerline (documentation [here](https://pro.arcgis.com/en/pro-app/tool-reference/topographic-production/polygon-to-centerline.htm)), but it's just for ArcGIS Pro. We could make this a Pro tool, but other than that, I don't see a way around that requirement.

There's an ET GeoWizards function that is supposed to do what we want, but using that requires a version-specific download, they don't support ArcGIS 10.6 yet, and I'm not sure that I can get that working without running the installer on any computer that we want to run the tool on. It would also mean relying on someone else to keep their code working for new versions, which obviously isn't ideal, and I'm not sure that the free version would do everything we would want it to (their description of the difference is pretty unclear.

With that in mind, I'm not seeing a lot of alternatives to asking the technician to provide a centerline. If @wally-mac or @G-Stevens has any other ideas, please, let me know.

**Comment by G-Stevens** [comment]
These are the tools I use to  create a centerline tool for a given polygon in this order not sure if this will help.
https://support.esri.com/en/technical-article/000012414 
https://github.com/Riverscapes/arcGNAT/tree/master/tools/FCT

**Comment by banderson1618** [comment]
The first link you gave me is the first one I linked. It needs some manual editing, which is why I don't think it would work for us.

The second one is interesting, though. One of the inputs is a stream network, which isn't ideal, but we could work with that if we needed to. That said, it might be easier for the technician to make the centerline than to find a stream network that works. I'll look into it, and update based on my findings.

**Comment by joewheaton** [comment]
This functionality exists in RBT... Ask Philip...

**Comment by banderson1618** [comment]
I had a chat with Philip over email and and reviewed the code in RBT. The centerline tool there requires a thalweg, which in turn requires inflow and outflow points and a DEM in order to find. It seems much simpler to me to just ask the user for a centerline, found via the steps at the ESRI support page [here](https://support.esri.com/en/technical-article/000012414). Unless someone advises differently, I'm going to add a centerline argument to the tool.
